before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
